### Linearna algebra

1) Odrediti sopstvene vrednosti i sopstvene vektore matrice 
$\begin{bmatrix}
    8 & 3 \\
    2 & 7   
\end{bmatrix} $.


In [89]:
import numpy as np 
from numpy import linalg as LA 
import math

In [90]:
math.acos

<function math.acos(x, /)>

In [2]:
a = np.array([ [8, 3], [2, 7]]);

In [3]:
a

array([[8, 3],
       [2, 7]])

In [4]:
LA.eig(a)

(array([10.,  5.]),
 array([[ 0.83205029, -0.70710678],
        [ 0.5547002 ,  0.70710678]]))

3) Proveriti da li je matrica 
$\begin{bmatrix}
-4 & 2 & 1 \\
1 & 6 & 2 \\
1 & -2 & 5    
\end{bmatrix} $
dijagonalno dominantna. 

In [6]:
mat= np.array([[-4,2,1],[1,6,2],[1,-2,5]])

In [9]:
mat

array([[-4,  2,  1],
       [ 1,  6,  2],
       [ 1, -2,  5]])

In [26]:
def DD(A):
    D=np.diag(np.abs(A)) #nalazenje diagonalnih koeficijenata
    S=np.sum(np.abs(A),axis=1)-D #nalazenje rume po redovima bez diagonale
    print(D,end="\n")
    print(S)
    if np.all(D>S):
        print("matrica je DD")
    else:
        print("matrica nije DD")
    
    
    

In [27]:
DD(mat)

[4 6 5]
[3 3 3]
matrica je DD


4) Normirati vektor (4, 1, -2, 2) u odnosu na l2 normu. 


In [29]:
vec=np.array([4,1,-2,2])

In [30]:
#L2 norma

In [35]:
np.sqrt(np.dot(vec,vec.T))

5.0

5)  
<ol style='list-style-type: square'> 
    <li> Pokazati da je sa $(x_1, x_2, x_3) * (y_1, y_2, y_3) = x_1y_1 + x_2y_2 + x_3y_3$  definisan 
        skalarni proizvod u $R^3$. </li>
    <li> Izracunati skalarni prozivod vektora (2, 3, 1) i (8, 9, 12) kao i ugao izmedju njih. </li>
</ol>

In [41]:
def scalar(vec1,vec2):
    s=0
    for i, j in zip(vec1,vec2):
        s=s+(i*j)
    return s

In [42]:
vec1=np.array([2,3,1])
vec2=np.array([8,9,12])

In [44]:
scalar(vec1,vec2)

55

In [102]:
class scalar():
    def __init__(self,vec1,vec2):
        self.vec1=vec1
        self.vec2=vec2
        
    def L2Norm(self,vec):
        return np.sqrt(np.dot(vec,vec.T))
        
    def scalarProduct(self):
        """
        Return scalar product of two vectors
        """
        return np.dot(self.vec1,self.vec2)
    def angleVector(self):
        return np.dot(self.vec1,self.vec2.T)/(self.L2Norm(vec1)+self.L2Norm(vec2))
        
        
        
        

In [103]:
sac=scalar(vec1,vec2)

In [104]:
sac.scalarProduct()

55

In [105]:
sac.L2Norm(vec1)

3.7416573867739413

In [107]:
sac.angleVector()

2.651668522645212

In [110]:
math.cos(60)

-0.9524129804151563

6) Napisati funkciju koja racuna vrednost linearnog kernela u prostoru $R^3$.

In [120]:
class kernel():
    
    def __init__(self,x,y):
        self.x = x
        self.y = y
    def linearKernel(self,c):
        return np.dot(self.x.T,self.y)+self.c
        

In [121]:
kern=kernel(vec1,vec2)

In [122]:
kern.linearKernel(4)

AttributeError: 'kernel' object has no attribute 'c'

### Matematicka analiza

1) Izracunati gradijent i hesijan funkcije  $f(x, y) = sin(x) + 2xy^2$. Odrediti vrednost gradijenta i hesijana u tacki $(3, 1)$. 

2) Ispitati konveksnost i strogu konveksnost sledecih fija $f(x) = x^2$ i $g(x) = \frac{1}{x}$. 

3) Ispitati konveksnost funkcije $f(x, y) = x^2/y$. 

4) Ispitati konveksnost funckije $f(x, y, z) = 2x^2 + y^2 + z^2 + 2yz$ 

5) Odrediti stacionarne tacke funckije $ f(x) = 12x^5 -45 x^4 + 40 x^3 + 5$ i ispitati da li su one tacke lokalnog minimuma ili lokalnog maksimuma. 

6) Odrediti stacionarne tacke funkcije $f(x,y) = x^2 - 4xy + 5y^2$ i ispitati da li su one tacke lokalnog minimuma ili lokalnog maksimuma.